# This is a basic workflow to help you get started with Actions

name: Eggplant Runner Demo

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Eggplant Runner
        uses: keysight-eggplant/eggplant-github-action@v1.0.2
        with:
          serverURL: "http://localhost:8000/"
          testConfigID: "2b43fd4b-c576-4f6e-9112-7b56131459aa"
          clientID: "client:dai:agent:integration"
          clientSecret: "249daf3f-2a7a-4072-9b63-15f393a4ba4a"
          
