# This is a basic workflow to help you get started with Actions

name: Eggplant Runner Demo

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Eggplant Runner
        uses: keysight-eggplant/eggplant-github-action@v1.0.4
        with:
          serverURL: "https://eggplant-partners.dai.eggplant.cloud"
          testConfigID: "b8f4d9d1-01c0-47c5-b1c4-155b625dbb8e"
          clientID: "client:dai:agent:integration"
          clientSecret: "d3cdb576-e636-4198-b550-e4f09be44a2e"
          
